import { supabase } from './supabase.js';
const $=id=>document.getElementById(id); let products=[]; let editingProduct=null,editingPost=null,editingPage=null;
async function isAdmin(){const {data:{user}}=await supabase.auth.getUser(); if(!user)return false; const {data}=await supabase.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle(); return !!data;}
async function boot(){if(await isAdmin())showPanel(); else { $('login').hidden=false; $('panel').hidden=true; }}
function showPanel(){ $('login').hidden=true; $('panel').hidden=false; loadAll(); }
supabase.auth.onAuthStateChange(()=>setTimeout(boot,0)); $('loginBtn').onclick=async()=>{const {error}=await supabase.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('loginMsg').textContent=error?error.message:'Checking admin access…';await boot();}; $('logout').onclick=()=>supabase.auth.signOut();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.hidden=true);$('tab-'+b.dataset.tab).hidden=false});
async function loadAll(){await Promise.all([loadSite(),loadProducts(),loadPosts(),loadPages(),loadAds()]);}
async function one(table){const {data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false});if(error)throw error;return data||[];}
async function loadSite(){const {data}=await supabase.from('site_settings').select('*').limit(1).maybeSingle();if(!data)return;[['siteName','site_name'],['tagline','tagline'],['logoUrl','logo_url'],['primaryColor','primary_color'],['accentColor','accent_color'],['heroTitle','hero_title'],['heroText','hero_text'],['heroButton','hero_button'],['footerText','footer_text'],['seoTitle','seo_title'],['seoDescription','seo_description']].forEach(([a,b])=>$(a).value=data[b]||'');}
$('siteForm').onsubmit=async e=>{e.preventDefault();const row={site_name:$('siteName').value,tagline:$('tagline').value,logo_url:$('logoUrl').value,primary_color:$('primaryColor').value,accent_color:$('accentColor').value,hero_title:$('heroTitle').value,hero_text:$('heroText').value,hero_button:$('heroButton').value,footer_text:$('footerText').value,seo_title:$('seoTitle').value,seo_description:$('seoDescription').value,updated_at:new Date().toISOString()};const {data:old}=await supabase.from('site_settings').select('id').limit(1).maybeSingle();const q=old?supabase.from('site_settings').update(row).eq('id',old.id):supabase.from('site_settings').insert(row);const {error}=await q;if(error)alert(error.message);else alert('Website settings saved');};
async function loadProducts(){products=await one('products');$('adminProducts').innerHTML=products.map(p=>`<div class="admin-card"><img src="${esc(p.image_url)}"><div><b>${esc(p.name)}</b><br><small>${esc(p.category)} · ₹${Number(p.price).toLocaleString('en-IN')}</small></div><div class="admin-actions"><button data-edit-p="${p.id}">Edit</button><button class="danger" data-del-p="${p.id}">Delete</button></div></div>`).join('')||'<p>No products.</p>';document.querySelectorAll('[data-edit-p]').forEach(b=>b.onclick=()=>editProduct(+b.dataset.editP));document.querySelectorAll('[data-del-p]').forEach(b=>b.onclick=()=>deleteProduct(+b.dataset.delP));}
$('productForm').onsubmit=async e=>{e.preventDefault();const row={name:$('pname').value,category:$('pcategory').value,price:Number($('pprice').value),image_url:$('pimage').value,buy_url:$('pbuy').value,description:$('pdesc').value,featured:$('pfeatured').checked,updated_at:new Date().toISOString()};const q=editingProduct?supabase.from('products').update(row).eq('id',editingProduct):supabase.from('products').insert(row);const {error}=await q;if(error)alert(error.message);else{resetProduct();loadProducts();loadProductChecks();}};function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;editingProduct=id;[['pname',p.name],['pcategory',p.category],['pprice',p.price],['pimage',p.image_url],['pbuy',p.buy_url],['pdesc',p.description||'']].forEach(([a,v])=>$(a).value=v);$('pfeatured').checked=!!p.featured;document.querySelector('[data-tab="products"]').click();scrollTo(0,0);}async function deleteProduct(id){if(!confirm('Delete this product?'))return;const {error}=await supabase.from('products').delete().eq('id',id);if(error)alert(error.message);else loadProducts();}function resetProduct(){editingProduct=null;$('productForm').reset();} $('cancelProduct').onclick=resetProduct;
async function loadProductChecks(selected=[]){products=await one('products');$('productChecks').innerHTML='<p><b>Related products</b></p>'+products.map(p=>`<label class="check"><input type="checkbox" value="${p.id}" ${selected.includes(p.id)?'checked':''}> ${esc(p.name)}</label>`).join('');}
async function loadPosts(){const {data,error}=await supabase.from('posts').select('*').order('created_at',{ascending:false});if(error){console.error(error);return;}const posts=data||[];$('adminPosts').innerHTML=posts.map(p=>`<div class="admin-card"><div><b>${esc(p.title)}</b><br><small>${esc(p.slug)} · ${p.published?'Published':'Draft'}</small></div><div class="admin-actions"><button data-edit-post="${p.id}">Edit</button><button class="danger" data-del-post="${p.id}">Delete</button></div></div>`).join('')||'<p>No posts.</p>';document.querySelectorAll('[data-edit-post]').forEach(b=>b.onclick=()=>editPost(+b.dataset.editPost));document.querySelectorAll('[data-del-post]').forEach(b=>b.onclick=()=>deletePost(+b.dataset.delPost));await loadProductChecks();}
async function editPost(id){const {data:p}=await supabase.from('posts').select('*').eq('id',id).single();const {data:links}=await supabase.from('post_products').select('product_id').eq('post_id',id);editingPost=id;[['postTitle',p.title],['postSlug',p.slug],['postImage',p.image_url||''],['postExcerpt',p.excerpt||''],['postContent',p.content||'']].forEach(([a,v])=>$(a).value=v);$('postPublished').checked=p.published;await loadProductChecks((links||[]).map(x=>x.product_id));document.querySelector('[data-tab="posts"]').click();scrollTo(0,0);}
$('postForm').onsubmit=async e=>{e.preventDefault();const slug=$('postSlug').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const row={title:$('postTitle').value,slug, image_url:$('postImage').value,excerpt:$('postExcerpt').value,content:$('postContent').value,published:$('postPublished').checked,updated_at:new Date().toISOString()};let postId=editingPost;let result=editingPost?await supabase.from('posts').update(row).eq('id',editingPost).select().single():await supabase.from('posts').insert(row).select().single();if(result.error){alert(result.error.message);return;}postId=result.data.id;await supabase.from('post_products').delete().eq('post_id',postId);const ids=[...document.querySelectorAll('#productChecks input:checked')].map(x=>({post_id:postId,product_id:+x.value}));if(ids.length)await supabase.from('post_products').insert(ids);resetPost();loadPosts();};function resetPost(){editingPost=null;$('postForm').reset();$('postPublished').checked=true;}$('cancelPost').onclick=resetPost;async function deletePost(id){if(!confirm('Delete this post?'))return;const {error}=await supabase.from('posts').delete().eq('id',id);if(error)alert(error.message);else loadPosts();}
async function loadPages(){const {data,error}=await supabase.from('pages').select('*').order('updated_at',{ascending:false});if(error)return;const pages=data||[];$('adminPages').innerHTML=pages.map(p=>`<div class="admin-card"><div><b>${esc(p.title)}</b><br><small>${esc(p.slug)}</small></div><div class="admin-actions"><button data-edit-page="${p.id}">Edit</button><button class="danger" data-del-page="${p.id}">Delete</button></div></div>`).join('')||'<p>No pages.</p>';document.querySelectorAll('[data-edit-page]').forEach(b=>b.onclick=()=>editPage(+b.dataset.editPage));document.querySelectorAll('[data-del-page]').forEach(b=>b.onclick=()=>deletePage(+b.dataset.delPage));}
$('pageForm').onsubmit=async e=>{e.preventDefault();const row={title:$('pageTitle').value,slug:$('pageSlug').value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),content:$('pageContent').value,published:$('pagePublished').checked,updated_at:new Date().toISOString()};const q=editingPage?supabase.from('pages').update(row).eq('id',editingPage):supabase.from('pages').insert(row);const {error}=await q;if(error)alert(error.message);else{editingPage=null;$('pageForm').reset();$('pagePublished').checked=true;loadPages();}};async function editPage(id){const {data:p}=await supabase.from('pages').select('*').eq('id',id).single();editingPage=id;[['pageTitle',p.title],['pageSlug',p.slug],['pageContent',p.content||'']].forEach(([a,v])=>$(a).value=v);$('pagePublished').checked=p.published;document.querySelector('[data-tab="pages"]').click();}async function deletePage(id){if(!confirm('Delete this page?'))return;await supabase.from('pages').delete().eq('id',id);loadPages();}
async function loadAds(){const {data}=await supabase.from('adsense_settings').select('*').limit(1).maybeSingle();if(!data)return;$('adsEnabled').checked=data.enabled;$('publisherId').value=data.publisher_id||'';$('homeSlot').value=data.homepage_slot||'';$('postSlot').value=data.post_slot||'';$('productSlot').value=data.product_slot||'';}
$('adsForm').onsubmit=async e=>{e.preventDefault();const row={enabled:$('adsEnabled').checked,publisher_id:$('publisherId').value,homepage_slot:$('homeSlot').value,post_slot:$('postSlot').value,product_slot:$('productSlot').value,updated_at:new Date().toISOString()};const {data:old}=await supabase.from('adsense_settings').select('id').limit(1).maybeSingle();const {error}=old?await supabase.from('adsense_settings').update(row).eq('id',old.id):await supabase.from('adsense_settings').insert(row);if(error)alert(error.message);else alert('AdSense settings saved');};
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}boot();
