-- NovaCart 3.0 migration. Run this whole script once in Supabase SQL Editor.
-- It upgrades the existing schema without requiring the old Pages UI.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, role text not null default 'admin' check (role='admin'), created_at timestamptz not null default now());
create table if not exists public.site_settings (id bigint generated by default as identity primary key, site_name text not null default 'NovaCart', logo_url text default '', favicon_url text default '', primary_color text default '#7c6cff', secondary_color text default '#43dcff', background_color text default '#07080d', text_color text default '#f5f6fa', hero_title text default 'Products that stand out.', hero_subtitle text default 'Discover trending products with direct buying links.', hero_button_text text default 'Explore ↗', hero_button_url text default '#products', footer_text text default 'NovaCart · Free product discovery store', seo_title text default 'NovaCart', seo_description text default 'Free product discovery store', updated_at timestamptz not null default now());
create table if not exists public.products (id bigint generated by default as identity primary key, name text not null, category text not null, price numeric not null default 0, image_url text not null, buy_url text not null, description text default '', featured boolean not null default false, created_at timestamptz not null default now());
alter table public.products add column if not exists featured boolean not null default false;
create table if not exists public.posts (id bigint generated by default as identity primary key, title text not null, slug text not null, image_url text default '', category text default '', excerpt text default '', content text default '', published boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists posts_slug_unique on public.posts(slug);
create table if not exists public.post_products (post_id bigint not null references public.posts(id) on delete cascade, product_id bigint not null references public.products(id) on delete cascade, created_at timestamptz not null default now(), primary key(post_id,product_id));
create table if not exists public.navigation (id bigint generated by default as identity primary key, label text not null, url text not null, location text not null default 'header', sort_order integer not null default 0, visible boolean not null default true, created_at timestamptz not null default now());
alter table public.navigation add column if not exists visible boolean not null default true;
create table if not exists public.adsense_settings (id bigint generated by default as identity primary key, enabled boolean not null default false, publisher_id text default '', homepage_slot text default '', post_slot text default '', product_slot text default '', show_homepage_ads boolean not null default false, show_post_ads boolean not null default false, show_product_ads boolean not null default false, updated_at timestamptz not null default now());

insert into public.site_settings default values on conflict do nothing;
insert into public.adsense_settings default values on conflict do nothing;

alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.products enable row level security;
alter table public.posts enable row level security;
alter table public.post_products enable row level security;
alter table public.navigation enable row level security;
alter table public.adsense_settings enable row level security;

create or replace function public.is_admin() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.admin_users a where a.user_id=auth.uid() and a.role='admin'); $$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- Rebuild policies so old overly-broad authenticated write policies do not block/override the admin-only design.
do $$ declare r record; begin for r in select policyname,tablename from pg_policies where schemaname='public' and tablename in ('admin_users','site_settings','products','posts','post_products','navigation','adsense_settings') loop execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename); end loop; end $$;

create policy admin_self_read on public.admin_users for select to authenticated using (user_id=auth.uid());
create policy public_site_read on public.site_settings for select to anon,authenticated using (true);
create policy admin_site_write on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy public_product_read on public.products for select to anon,authenticated using (true);
create policy admin_product_write on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy public_post_read on public.posts for select to anon,authenticated using (published=true or public.is_admin());
create policy admin_post_write on public.posts for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy public_post_products_read on public.post_products for select to anon,authenticated using (true);
create policy admin_post_products_write on public.post_products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy public_navigation_read on public.navigation for select to anon,authenticated using (visible=true or public.is_admin());
create policy admin_navigation_write on public.navigation for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy public_adsense_read on public.adsense_settings for select to anon,authenticated using (true);
create policy admin_adsense_write on public.adsense_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Optional starter navigation. Only inserts when the table is empty.
insert into public.navigation(label,url,location,sort_order,visible) select 'Products','#products','header',10,true where not exists(select 1 from public.navigation);
insert into public.navigation(label,url,location,sort_order,visible) select 'Posts','#posts','header',20,true where not exists(select 1 from public.navigation where label='Posts');

-- Pages are intentionally no longer used by NovaCart 3.0. The old pages table is left intact to avoid deleting existing data.
