-- Run this in Supabase SQL Editor.
create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null,
 category text not null,
 price numeric not null default 0,
 image_url text not null,
 buy_url text not null,
 description text default '',
 created_at timestamptz default now()
);
alter table public.products enable row level security;

create policy "public can view products" on public.products
for select to anon, authenticated using (true);

create policy "authenticated can insert products" on public.products
for insert to authenticated with check (true);

create policy "authenticated can update products" on public.products
for update to authenticated using (true) with check (true);

create policy "authenticated can delete products" on public.products
for delete to authenticated using (true);

insert into public.products (name,category,price,image_url,buy_url,description) values
('AeroPods Pro','Electronics',2499,'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1000&q=85','#','Wireless earbuds — replace with your real product.'),
('Orbit Smart Watch','Accessories',3999,'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85','#','Smartwatch — replace with your real product.');