import { supabase } from "./supabase.js";
const WA="919999999999";let products=[],posts=[],settings=null,cart=JSON.parse(localStorage.novacart||"[]");const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function load(){try{const [pr,po,st,nv,ad]=await Promise.all([supabase.from('products').select('*').order('created_at',{ascending:false}),supabase.from('posts').select('*').eq('published',true).order('created_at',{ascending:false}),supabase.from('site_settings').select('*').limit(1).maybeSingle(),supabase.from('navigation').select('*').eq('visible',true).order('sort_order',{ascending:true}),supabase.from('adsense_settings').select('*').limit(1).maybeSingle()]);if(pr.error)throw pr.error;if(po.error)throw po.error;products=pr.data||[];posts=po.data||[];settings=st.data||null;applySite();renderNav(nv.data||[]);renderCats();render(products.filter(p=>p.featured));renderPosts();renderAds(ad.data);updateCart()}catch(e){console.error(e);document.querySelector('#productsGrid').innerHTML='<p>Unable to load the store right now.</p>'}}
function applySite(){if(!settings)return;document.title=settings.seo_title||settings.site_name||'NovaCart';document.querySelector('#metaDescription').content=settings.seo_description||'';if(settings.site_name)document.querySelector('#siteLogo').textContent=settings.site_name;if(settings.hero_title)document.querySelector('#heroTitle').innerHTML=esc(settings.hero_title).replace(/
/g,'<br>');if(settings.hero_subtitle)document.querySelector('#heroText').textContent=settings.hero_subtitle;if(settings.hero_button_text)document.querySelector('#heroButton').textContent=settings.hero_button_text;if(settings.hero_button_url)document.querySelector('#heroButton').onclick=()=>location.href=settings.hero_button_url;if(settings.footer_text)document.querySelector('#footer').textContent=settings.footer_text;const root=document.documentElement;if(settings.primary_color)root.style.setProperty('--primary',settings.primary_color);if(settings.background_color)document.body.style.background=settings.background_color;if(settings.text_color)document.body.style.color=settings.text_color}
function renderNav(list){const nav=document.querySelector('#nav');nav.innerHTML=list.map(n=>`<a href="${esc(n.url)}">${esc(n.label)}</a>`).join('')||'<a href="#products">Products</a><a href="#posts">Posts</a>'}
function renderCats(){const cs=[...new Set(products.map(p=>p.category).filter(Boolean))];document.querySelector('#cats').innerHTML=cs.map(c=>`<div class="cat" data-cat="${esc(c)}"><b>${esc(c)}</b><small>${products.filter(p=>p.category===c).length} products</small></div>`).join('')||'<p>No products yet. Add them from Admin.</p>';document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>render(products.filter(p=>p.category===x.dataset.cat)))}
function render(list){document.querySelector('#productsGrid').innerHTML=(list||[]).map(p=>`<article class="card"><img src="${esc(p.image_url)}" alt="${esc(p.name)}"><div class="info"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><div class="row"><span class="price">${money(p.price)}</span><div><a class="buy" href="${esc(p.buy_url)}" target="_blank" rel="noopener">Buy ↗</a><button data-add="${p.id}">+ Bag</button></div></div></div></article>`).join('')||'<p>No products found.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add))}
function renderPosts(){document.querySelector('#postsGrid').innerHTML=posts.map(p=>`<article class="card"><img src="${esc(p.image_url||'')}" alt="${esc(p.title)}"><div class="info"><h3>${esc(p.title)}</h3><p>${esc(p.excerpt||'')}</p><a class="buy" href="post.html?slug=${encodeURIComponent(p.slug)}">Read post ↗</a></div></article>`).join('')||'<p>No posts yet.</p>'}
function renderAds(a){if(!a?.enabled||!a.show_homepage_ads||!a.publisher_id||!a.homepage_slot)return;const box=document.querySelector('#homeAd');box.innerHTML=`<ins class="adsbygoogle" style="display:block" data-ad-client="${esc(a.publisher_id)}" data-ad-slot="${esc(a.homepage_slot)}" data-ad-format="auto" data-full-width-responsive="true"></ins>`;const s=document.createElement('script');s.async=true;s.src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client='+encodeURIComponent(a.publisher_id);s.crossOrigin='anonymous';document.head.appendChild(s);s.onload=()=>{try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch(e){console.error(e)}}}
window.add=id=>{cart.push(Number(id));localStorage.novacart=JSON.stringify(cart);updateCart()};window.toggleCart=()=>document.querySelector('#cart').classList.toggle('open');window.removeItem=i=>{cart.splice(i,1);localStorage.novacart=JSON.stringify(cart);updateCart()};window.whatsapp=()=>{const items=cart.map(id=>products.find(p=>p.id==id)).filter(Boolean);if(!items.length)return;const msg='Hi! I want to order:%0A'+items.map(p=>`• ${encodeURIComponent(p.name)} — ${money(p.price)}`).join('%0A');location.href=`https://wa.me/${WA}?text=${msg}`};function updateCart(){document.querySelector('#count').textContent=cart.length;const items=cart.map(id=>products.find(p=>p.id==id)).filter(Boolean);document.querySelector('#cartItems').innerHTML=items.map((p,i)=>`<div class="item"><img src="${esc(p.image_url)}"><div><b>${esc(p.name)}</b><small>${money(p.price)}</small><br><button onclick="removeItem(${i})">Remove</button></div></div>`).join('')||'<p>Bag is empty.</p>';document.querySelector('#total').textContent=money(items.reduce((s,p)=>s+Number(p.price||0),0))}document.querySelector('#cartBtn').onclick=toggleCart;load();updateCart();
